title: Lachie Macdonald
logo: /assets/img/logo.png
description: Teacher & Computer Scientist.


linkedin_username: lachm99
github_username:  lachm99
mail_address: lachlanmac99@gmail.com
strava_username: lachm99

show_excerpts: true
show_downloads: false
google_analytics: true

theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
include: ['pages', 'projects']
